# Generated by Django 4.0.6 on 2022-11-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Empty description'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Location not provided', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
