# Generated by Django 4.0.6 on 2022-07-30 14:36

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=pathlib.PurePosixPath('/home/rodrigue/django/fotoblog/media/users/default.jpg'), upload_to='users'),
        ),
    ]
