# Generated by Django 4.0.6 on 2022-08-28 16:35

from django.db import migrations
from guardian.models import UserObjectPermission
from blog.models import Post,Photo
def assign_post_and_photo_permissions(apps,schema_migration):

    for p in Post.objects.all():
        UserObjectPermission.objects.assign_perm('change_post', p.author, obj=p)
        UserObjectPermission.objects.assign_perm('delete_post', p.author, obj=p)

    for p in Photo.objects.all():
        UserObjectPermission.objects.assign_perm('change_photo', p.uploader, obj=p)
        UserObjectPermission.objects.assign_perm('delete_photo', p.uploader, obj=p)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_follows'),
    ]

    operations = [
        migrations.RunPython(assign_post_and_photo_permissions)
    ]
