# Generated by Django 4.0.6 on 2022-11-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220828_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to='users'),
        ),
    ]
