# Generated by Django 4.0.6 on 2022-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='words_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
